setwd("D:\\data science\\R\\Rwork_coursera\\practice data\\exdata%2Fdata%2Fhousehold_power_consumption")
housing_cons<-read.delim(file='./household_power_consumption.txt',header = TRUE,sep = ';',stringsAsFactors = FALSE)
library(dplyr)
housing<-housing_cons%>%filter(Date %in% c('1/2/2007','2/2/2007'))
head(housing)
datetime<-paste(dmy(housing$Date),housing$Time)
housing$datetime<-as.POSIXct(datetime)
png("plot2.png",width = 480,height = 480)
with(housing,plot(Global_active_power~datetime,type="l",ylab = "Global Active Power (kilowatts)",xlab=""))
dev.off()
