setwd("D:\\data science\\R\\Rwork_coursera\\practice data\\exdata%2Fdata%2Fhousehold_power_consumption")
housing_cons<-read.delim(file='./household_power_consumption.txt',header=T, sep=';', na.strings="?", 
                         nrows=2075259, check.names=F, stringsAsFactors=F, comment.char="", quote='\"')
library(dplyr)
housing<-housing_cons%>%filter(Date %in% c('1/2/2007','2/2/2007'))
head(housing)
datetime<-paste(dmy(housing$Date),housing$Time)
housing$Datetime<-as.POSIXct(datetime)
png('plot4.png',width = 480,height = 480)
par(mfrow=c(2,2))
with(housing,plot(Global_active_power~Datetime,type="l",ylab = "Global Active Power (kilowatts)",xlab=""))
with(housing,plot(Voltage~Datetime,type="l",ylab="Voltage",xlab="datetime"))
with(housing,{
  plot(Sub_metering_1~Datetime,type="l",ylab="Energy sub metering",xlab="")
  lines(Sub_metering_2~Datetime,col='red')
  lines(Sub_metering_3~Datetime,col='blue')
})
legend('topright',col = c('black','red','blue'),lty=1,lwd=2,legend = c('Sub_metering_1','Sub_metering_2','Sub_metering_3'))
with(housing,plot(Global_reactive_power~Datetime,type="l",ylab = "Global_rective_power (kilowatts)",xlab=""))
dev.off()
